// Generated by npm run types:database. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: {
    Tables: {
      bills: { Row: { id: string; user_id: string; title: string; amount: number; category: string; due_day: number; paid_month: string | null; created_at: string; revision: number; payment_history: Json }; Insert: { id?: string; user_id: string; title: string; amount: number; category: string; due_day: number; paid_month?: string | null; created_at?: string; revision?: number; payment_history?: Json }; Update: { id?: string; user_id?: string; title?: string; amount?: number; category?: string; due_day?: number; paid_month?: string | null; created_at?: string; revision?: number; payment_history?: Json }; Relationships: [] };
      deleted_financial_records: { Row: { table_name: "transactions" | "bills" | "goals" | "subscriptions" | "splits"; record_id: string; user_id: string; deleted_at: string }; Insert: { table_name: "transactions" | "bills" | "goals" | "subscriptions" | "splits"; record_id: string; user_id: string; deleted_at?: string }; Update: { table_name?: "transactions" | "bills" | "goals" | "subscriptions" | "splits"; record_id?: string; user_id?: string; deleted_at?: string }; Relationships: [] };
      financial_operations: { Row: { id: string; user_id: string; bill_id: string; period: string; record_transaction: boolean; response: Json; created_at: string }; Insert: { id: string; user_id: string; bill_id: string; period: string; record_transaction: boolean; response: Json; created_at?: string }; Update: { id?: string; user_id?: string; bill_id?: string; period?: string; record_transaction?: boolean; response?: Json; created_at?: string }; Relationships: [] };
      goals: { Row: { id: string; user_id: string; template_id: string; name: string; target: number; saved: number; deadline: string | null; icon: string | null; color: string | null; notes: string; activity: Json; created_at: string; revision: number; starting_balance: number }; Insert: { id?: string; user_id: string; template_id?: string; name: string; target: number; saved?: number; deadline?: string | null; icon?: string | null; color?: string | null; notes?: string; activity?: Json; created_at?: string; revision?: number; starting_balance?: number }; Update: { id?: string; user_id?: string; template_id?: string; name?: string; target?: number; saved?: number; deadline?: string | null; icon?: string | null; color?: string | null; notes?: string; activity?: Json; created_at?: string; revision?: number; starting_balance?: number }; Relationships: [] };
      profiles: { Row: { id: string; name: string; school: string; created_at: string; updated_at: string; revision: number }; Insert: { id: string; name?: string; school?: string; created_at?: string; updated_at?: string; revision?: number }; Update: { id?: string; name?: string; school?: string; created_at?: string; updated_at?: string; revision?: number }; Relationships: [] };
      splits: { Row: { id: string; user_id: string; title: string; person: string; amount: number; direction: "owed_to_me" | "i_owe"; category: string; due_date: string | null; note: string; status: "open" | "settled"; settled_at: string | null; created_at: string; revision: number }; Insert: { id?: string; user_id: string; title: string; person: string; amount: number; direction: "owed_to_me" | "i_owe"; category?: string; due_date?: string | null; note?: string; status?: "open" | "settled"; settled_at?: string | null; created_at?: string; revision?: number }; Update: { id?: string; user_id?: string; title?: string; person?: string; amount?: number; direction?: "owed_to_me" | "i_owe"; category?: string; due_date?: string | null; note?: string; status?: "open" | "settled"; settled_at?: string | null; created_at?: string; revision?: number }; Relationships: [] };
      subscriptions: { Row: { id: string; user_id: string; service_id: string; name: string; amount: number; frequency: "weekly" | "monthly" | "yearly"; next_billing_date: string; category: string; reminder_days: number; notes: string; free_trial: boolean; icon: string | null; color: string | null; status: "active" | "paused"; created_at: string; revision: number }; Insert: { id?: string; user_id: string; service_id?: string; name: string; amount: number; frequency: "weekly" | "monthly" | "yearly"; next_billing_date: string; category?: string; reminder_days?: number; notes?: string; free_trial?: boolean; icon?: string | null; color?: string | null; status?: "active" | "paused"; created_at?: string; revision?: number }; Update: { id?: string; user_id?: string; service_id?: string; name?: string; amount?: number; frequency?: "weekly" | "monthly" | "yearly"; next_billing_date?: string; category?: string; reminder_days?: number; notes?: string; free_trial?: boolean; icon?: string | null; color?: string | null; status?: "active" | "paused"; created_at?: string; revision?: number }; Relationships: [] };
      transactions: { Row: { id: string; user_id: string; type: "income" | "expense"; amount: number; category: string; title: string; note: string; transaction_date: string; recurring: boolean; created_at: string; revision: number }; Insert: { id?: string; user_id: string; type: "income" | "expense"; amount: number; category: string; title: string; note?: string; transaction_date?: string; recurring?: boolean; created_at?: string; revision?: number }; Update: { id?: string; user_id?: string; type?: "income" | "expense"; amount?: number; category?: string; title?: string; note?: string; transaction_date?: string; recurring?: boolean; created_at?: string; revision?: number }; Relationships: [] };
      user_settings: { Row: { user_id: string; currency: "EUR" | "USD" | "GBP" | "HUF"; monthly_budget: number; notifications: boolean; category_budgets: Json; subscription_plan: "free" | "pro"; subscription_status: "inactive" | "active" | "canceled"; updated_at: string; revision: number; period_budgets: Json }; Insert: { user_id: string; currency?: "EUR" | "USD" | "GBP" | "HUF"; monthly_budget?: number; notifications?: boolean; category_budgets?: Json; subscription_plan?: "free" | "pro"; subscription_status?: "inactive" | "active" | "canceled"; updated_at?: string; revision?: number; period_budgets?: Json }; Update: { user_id?: string; currency?: "EUR" | "USD" | "GBP" | "HUF"; monthly_budget?: number; notifications?: boolean; category_budgets?: Json; subscription_plan?: "free" | "pro"; subscription_status?: "inactive" | "active" | "canceled"; updated_at?: string; revision?: number; period_budgets?: Json }; Relationships: [] };
    };
    Views: Record<never, never>;
    Functions: {
      delete_own_account: { Args: Record<never, never>; Returns: undefined };
      monthly_totals: { Args: { period: string }; Returns: { income: number; expenses: number; monthly_net: number }[] };
      record_bill_payment: { Args: { operation_id: string; bill_id: string; period: string; expected_revision: number; record_transaction: boolean; paid_at: string }; Returns: Json };
    };
    Enums: Record<never, never>; CompositeTypes: Record<never, never>;
  };
};
export type RowOf<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export const rowContracts = {
  "bills": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "title": {
      "type": "string",
      "nullable": false
    },
    "amount": {
      "type": "number",
      "nullable": false
    },
    "category": {
      "type": "string",
      "nullable": false
    },
    "due_day": {
      "type": "number",
      "nullable": false
    },
    "paid_month": {
      "type": "string",
      "nullable": true
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    },
    "payment_history": {
      "type": "json",
      "nullable": false
    }
  },
  "deleted_financial_records": {
    "table_name": {
      "type": "string",
      "nullable": false,
      "values": [
        "transactions",
        "bills",
        "goals",
        "subscriptions",
        "splits"
      ]
    },
    "record_id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "deleted_at": {
      "type": "string",
      "nullable": false
    }
  },
  "financial_operations": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "bill_id": {
      "type": "string",
      "nullable": false
    },
    "period": {
      "type": "string",
      "nullable": false
    },
    "record_transaction": {
      "type": "boolean",
      "nullable": false
    },
    "response": {
      "type": "json",
      "nullable": false
    },
    "created_at": {
      "type": "string",
      "nullable": false
    }
  },
  "goals": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "template_id": {
      "type": "string",
      "nullable": false
    },
    "name": {
      "type": "string",
      "nullable": false
    },
    "target": {
      "type": "number",
      "nullable": false
    },
    "saved": {
      "type": "number",
      "nullable": false
    },
    "deadline": {
      "type": "string",
      "nullable": true
    },
    "icon": {
      "type": "string",
      "nullable": true
    },
    "color": {
      "type": "string",
      "nullable": true
    },
    "notes": {
      "type": "string",
      "nullable": false
    },
    "activity": {
      "type": "json",
      "nullable": false
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    },
    "starting_balance": {
      "type": "number",
      "nullable": false
    }
  },
  "profiles": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "name": {
      "type": "string",
      "nullable": false
    },
    "school": {
      "type": "string",
      "nullable": false
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "updated_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    }
  },
  "splits": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "title": {
      "type": "string",
      "nullable": false
    },
    "person": {
      "type": "string",
      "nullable": false
    },
    "amount": {
      "type": "number",
      "nullable": false
    },
    "direction": {
      "type": "string",
      "nullable": false,
      "values": [
        "owed_to_me",
        "i_owe"
      ]
    },
    "category": {
      "type": "string",
      "nullable": false
    },
    "due_date": {
      "type": "string",
      "nullable": true
    },
    "note": {
      "type": "string",
      "nullable": false
    },
    "status": {
      "type": "string",
      "nullable": false,
      "values": [
        "open",
        "settled"
      ]
    },
    "settled_at": {
      "type": "string",
      "nullable": true
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    }
  },
  "subscriptions": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "service_id": {
      "type": "string",
      "nullable": false
    },
    "name": {
      "type": "string",
      "nullable": false
    },
    "amount": {
      "type": "number",
      "nullable": false
    },
    "frequency": {
      "type": "string",
      "nullable": false,
      "values": [
        "weekly",
        "monthly",
        "yearly"
      ]
    },
    "next_billing_date": {
      "type": "string",
      "nullable": false
    },
    "category": {
      "type": "string",
      "nullable": false
    },
    "reminder_days": {
      "type": "number",
      "nullable": false
    },
    "notes": {
      "type": "string",
      "nullable": false
    },
    "free_trial": {
      "type": "boolean",
      "nullable": false
    },
    "icon": {
      "type": "string",
      "nullable": true
    },
    "color": {
      "type": "string",
      "nullable": true
    },
    "status": {
      "type": "string",
      "nullable": false,
      "values": [
        "active",
        "paused"
      ]
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    }
  },
  "transactions": {
    "id": {
      "type": "string",
      "nullable": false
    },
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "type": {
      "type": "string",
      "nullable": false,
      "values": [
        "income",
        "expense"
      ]
    },
    "amount": {
      "type": "number",
      "nullable": false
    },
    "category": {
      "type": "string",
      "nullable": false
    },
    "title": {
      "type": "string",
      "nullable": false
    },
    "note": {
      "type": "string",
      "nullable": false
    },
    "transaction_date": {
      "type": "string",
      "nullable": false
    },
    "recurring": {
      "type": "boolean",
      "nullable": false
    },
    "created_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    }
  },
  "user_settings": {
    "user_id": {
      "type": "string",
      "nullable": false
    },
    "currency": {
      "type": "string",
      "nullable": false,
      "values": [
        "EUR",
        "USD",
        "GBP",
        "HUF"
      ]
    },
    "monthly_budget": {
      "type": "number",
      "nullable": false
    },
    "notifications": {
      "type": "boolean",
      "nullable": false
    },
    "category_budgets": {
      "type": "json",
      "nullable": false
    },
    "subscription_plan": {
      "type": "string",
      "nullable": false,
      "values": [
        "free",
        "pro"
      ]
    },
    "subscription_status": {
      "type": "string",
      "nullable": false,
      "values": [
        "inactive",
        "active",
        "canceled"
      ]
    },
    "updated_at": {
      "type": "string",
      "nullable": false
    },
    "revision": {
      "type": "number",
      "nullable": false
    },
    "period_budgets": {
      "type": "json",
      "nullable": false
    }
  }
} as const;
