const { test, expect } = require('@playwright/test');
const { createClient } = require('@supabase/supabase-js');
const { randomUUID } = require('node:crypto');
const { isolatedProject } = require('../scripts/isolated-project.cjs');
const AxeBuilder = require('@axe-core/playwright').default;
const options = { auth: { persistSession: false, autoRefreshToken: false } };
let admin, deviceB, user, email, password;
test.beforeAll(async () => {
  const project = isolatedProject();
  admin = createClient(project.url, project.serviceKey, options);
  deviceB = createClient(project.url, project.publicKey, options);
  email = `pocketwise-browser-${randomUUID()}@example.com`; password = `Pocketwise-${randomUUID()}!`;
  const created = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (created.error) throw created.error;
  user = created.data.user;
  const signedIn = await deviceB.auth.signInWithPassword({ email, password });
  if (signedIn.error) throw signedIn.error;
});
test.afterAll(async () => {
  if (user) {
    const { error } = await admin.auth.admin.deleteUser(user.id);
    if (error) throw error;
  }
  if (deviceB) await deviceB.auth.signOut({ scope: 'local' });
});
test('authenticated financial workflows, two-device resume, deleted draft and failed request recovery', async ({ page }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeVisible();
  await page.getByLabel('Add a transaction', { exact: true }).click();
  await page.getByLabel('Description', { exact: true }).fill('Authenticated expense');
  await page.getByLabel('Amount', { exact: true }).fill('12.34');
  await page.getByRole('button', { name: 'Save expense', exact: true }).click();
  await page.getByRole('tab', { name: /Activity/ }).click();
  await expect(page.getByText('Authenticated expense', { exact: true })).toBeVisible();
  const rows = await deviceB.from('transactions').select().eq('user_id', user.id);
  if (rows.error) throw rows.error;
  const item = rows.data[0];
  const changed = await deviceB.from('transactions').update({ title: 'Device B changed expense', revision: item.revision + 1 }).eq('id', item.id);
  if (changed.error) throw changed.error;
  // Real PostgREST mutation + browser focus event. Native background/resume still needs devices.
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await expect(page.getByText('Device B changed expense', { exact: true })).toBeVisible();
  await page.getByText('Device B changed expense', { exact: true }).click();
  await page.getByLabel('Description', { exact: true }).fill('Preserved deleted draft');
  const removed = await deviceB.from('transactions').delete().eq('id', item.id);
  if (removed.error) throw removed.error;
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByLabel('Description', { exact: true })).toHaveValue('Preserved deleted draft');
  await expect(page.getByText(/This record was deleted on another device/)).toBeVisible();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('tab', { name: /Budgets/ }).click();
  await page.getByRole('button', { name: 'Add bill', exact: true }).first().click();
  await page.getByLabel('Bill name', { exact: true }).fill('Authenticated bill');
  await page.getByLabel('Amount', { exact: true }).fill('9.99');
  await page.getByLabel('Due day 1–31', { exact: true }).fill('3');
  await page.getByRole('button', { name: 'Save monthly bill', exact: true }).click();
  await page.getByRole('button', { name: 'Record payment for Authenticated bill', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: /Authenticated bill paid for/ })).toBeChecked();
  await page.getByRole('button', { name: 'Edit Authenticated bill', exact: true }).click();
  await expect(page.getByText(/— marked paid/)).toBeVisible(); await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.route('**/rest/v1/**', (route) => route.abort());
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByText(/Cloud load failed/).first()).toBeVisible();
  await page.unroute('**/rest/v1/**');
  await page.getByRole('button', { name: 'Reload', exact: true }).click();
  await expect(page.getByText(/Cloud load failed/)).toHaveCount(0);
  await page.getByRole('tab', { name: /Profile/ }).click();
  await page.getByText('Subscriptions', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Add subscription', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Authenticated subscription');
  await page.getByLabel('Amount', { exact: true }).fill('4.25');
  await page.getByRole('button', { name: 'Track subscription', exact: true }).click();
  await page.getByRole('button', { name: 'Pause Authenticated subscription', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Resume Authenticated subscription', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByText('Savings goals', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Add savings goal', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Authenticated goal');
  await page.getByLabel('Savings target', { exact: true }).fill('500');
  await page.getByLabel('Starting saved balance', { exact: true }).fill('215');
  await page.getByRole('button', { name: 'Create savings goal', exact: true }).click();
  await page.getByText('Authenticated goal', { exact: true }).click();
  await page.getByRole('button', { name: 'Withdraw', exact: true }).click();
  await page.getByLabel('Contribution amount', { exact: true }).fill('25');
  await page.getByLabel('Contribution note', { exact: true }).fill('Authenticated withdrawal');
  await page.getByRole('button', { name: 'Record withdrawal', exact: true }).click();
  await expect(page.getByText('Authenticated withdrawal', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByText('Split costs', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Add personal debt', exact: true }).click();
  await page.getByLabel('Description', { exact: true }).fill('Authenticated debt');
  await page.getByLabel('Person', { exact: true }).fill('Isolated Taylor');
  await page.getByLabel('Amount', { exact: true }).fill('15.50');
  await page.getByRole('button', { name: 'Track shared expense', exact: true }).click();
  await page.getByRole('button', { name: 'Mark balance settled for Authenticated debt', exact: true }).click();
  await expect(page.getByText('Recently settled', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByText('Privacy & data', { exact: true }).click();
  const exported = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export JSON', exact: true }).click();
  expect((await exported).suggestedFilename()).toMatch(/\.json$/);
  expect(errors).toEqual([]);
});

test('real browser recovery link, recovery screen at every target width, and password replacement', async ({ page }) => {
  const { data, error } = await admin.auth.admin.generateLink({ type: 'recovery', email, options: { redirectTo: 'http://127.0.0.1:4173/?recovery=1' } });
  if (error) throw error;
  await page.goto(data.properties.action_link);
  await expect(page.getByText('Choose a new password', { exact: true })).toBeVisible();
  for (const width of [360, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await page.screenshot({ path: `test-results/recovery-${width}.png` });
    const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze();
    expect(results.violations).toEqual([]);
  }
  const replacement = `${password}-new`;
  await page.getByLabel('New password', { exact: true }).fill(replacement);
  await page.getByLabel('Confirm new password', { exact: true }).fill('mismatch');
  await expect(page.getByRole('button', { name: 'Save new password', exact: true })).toBeDisabled();
  await page.getByLabel('Confirm new password', { exact: true }).fill(replacement);
  await page.getByRole('button', { name: 'Save new password', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeVisible();
  const signedIn = await deviceB.auth.signInWithPassword({ email, password: replacement });
  if (signedIn.error) throw signedIn.error;
});
